### ISSUE TITLE
Subdissector example

### ISSUE THREAD

**Issue by nefethael** [whitequark/zmtp-wireshark#14]
Hi, 

Would it be possible to include a basic subdissector example or add some pointers in documentation?
I'm trying to add protobuf to wtmp subdissector without success. 

Regards,
Vincent

**Comment by whitequark** [comment]
I wrote this so long, I forgot. Sorry. Try asking on Wireshark support channels.

**Comment by nefethael** [comment]
@whitequark Ok no problem, thanks for answer.
