### ISSUE TITLE
Can't find ZMTP "Decode as" in Wireshark v3.2.1

### ISSUE THREAD

**Issue by yoshihiro-darkness** [whitequark/zmtp-wireshark#16]
Hello, I am new user for this. 
Now I can't find the ZMTP  in the list of "Decode as"  in my Wireshark.
But  in "Analyze" → "Enabled Protocols"  I can find ZMTP.. 
So I wonder why I am like this situation. 

Any help/support appreciated.

**Comment by synfinatic** [comment]
I ran into the same issue.  I checkout the previous version which automatically detected ZMTP running on 5556.  Looks like the previous version also allows you to change the tcp port(s) if you're running on a different port.

**Comment by yoshihiro-darkness** [comment]
> I ran into the same issue. I checkout the previous version which automatically detected ZMTP running on 5556. Looks like the previous version also allows you to change the tcp port(s) if you're running on a different port.

Dear Aaron, Thank you for your feedback. May I know which Wireshark version works fine with "zmtp-wireshark"? I really need to use this lua.

thanks!

**Comment by synfinatic** [comment]
3.2.1 is what is working for me.  But like I said, you gotta checkout the previous commit of this repo.  The current version seems broken.

**Comment by whitequark** [comment]
cc @pulkomandy

**Comment by yoshihiro-darkness** [comment]
> 3.2.1 is what is working for me. But like I said, you gotta checkout the previous commit of this repo. The current version seems broken.

Dear Aaron, thank you I got misunderstood your previous answer since I am not good at English. okay I would try it.

Thanks,

**Comment by yoshihiro-darkness** [comment]
commit 0702cc445cc80cdec55305c46fc2f97db9c00075

It works for me with Wireshark v3.2.1

thanks!!

**Comment by pulkomandy** [comment]
I think it needs a DissectorTable.get(tcp.port).add_for_decode_as(zmtp_dissector). I guess this was done implicitly by registering a port range before?

**Comment by whitequark** [comment]
Could you prepare a PR to fix this?

**Comment by pulkomandy** [comment]
Yes, but not until I get back from vacation in about 2 weeks and can test things on the computer where I have this set up
