### ISSUE TITLE
Request for PDU tracking is blocking TCP reassembly

### ISSUE THREAD

**Issue by mamoch** [whitequark/zmtp-wireshark#18]
https://github.com/whitequark/zmtp-wireshark/blob/0f112fdf95771ea3c3fdd6e64c824929ac0bdf6c/zmtp-dissector.lua#L491-L498

The request for PDU tracking is blocking TCP reassembly, if there are more than two segments. The reassembly is already requested by desegment_offset and desegment_len, which works fine, if there is no PDU tracking.

A description for TCP reassembly can be found here:
[Lua/Dissectors – TCP reassembly](https://wiki.wireshark.org/Lua/Dissectors#TCP_reassembly)
and a tutorial here:
[A dissector tutorial with TCP-reassembly](https://wiki.wireshark.org/Lua/Examples#A_dissector_tutorial_with_TCP-reassembly)

**Comment by whitequark** [comment]
I haven't used this plugin myself in five years. Feel free to submit a pull request.

**Comment by mamoch** [comment]
Wireshark capture test data:
[zmtp_tcp_reassembly.zip](https://github.com/whitequark/zmtp-wireshark/files/4788600/zmtp_tcp_reassembly.zip)
(use “Decode As...” ZMTP for TCP port 5566)

**Comment by mamoch** [comment]
Actually, I had prepared that already… ;-)

**Comment by whitequark** [comment]
Cool, thank you!

**Comment by whitequark** [comment]
Fixed by #19.
