### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ewa** [whitequark/zmtp-wireshark#23]
Hi, I have a general question:  Is this being maintained / are any of the existing developers interested in or available for fixing stuff?  I've run into some weirdness for which the fixes aren't obvious (to me).  Thanks!

**Comment by whitequark** [comment]
Passively maintained. I'll merge PRs that look good at a quick glance, but probably won't put in more effort.

**Comment by ewa** [comment]
Good to know.  I ended up shelving what I was working on (a dissector for an in-house custom protocol that runs on top of ZMQ) for now, but if I come back to it and end up working on this dissector, I'll let you know.  Thanks!

**Comment by whitequark** [comment]
Sounds good to me!

**Comment by MartinMathieson** [comment]
I realise this was almost a year ago, but wanted to make you aware of https://gitlab.com/wireshark/wireshark/-/merge_requests/14947, where I am looking into merging a built-in C dissector for this protocol.

Eric, if you are still involved with ZeroMQ, any testing, comments, captures would be welcome.  One thing that a built-in dissector will solve is the order of loading other plugins that register for the dissector table, but it also lets you add the mappings into table (which can them be shared by importing/exporting Wireshark profiles).
