### ISSUE TITLE
Error when using Wireshark 2.0

### ISSUE THREAD

**Issue by greydot** [whitequark/zmtp-wireshark#4]
After upgrading to Wireshark 2.0, I get this error when trying to decode a ZMQ stream.

Expert Info (Error/Undecoded): Lua Error: [string "/home/void/.wireshark/plugins/zmtp-wireshar..."]:397: attempt to index global 'bit32' (a nil value)

**Comment by whitequark** [comment]
Sorry, I have no time to fix this any time soon.

**Comment by whitequark** [comment]
Ah, it seems like you're now supposed to use Lua 5.3 [internal bitwise operations](http://www.lua.org/manual/5.3/manual.html#3.4.2) in Wireshark 2.0. This should be a trivial fix.
